export const REGISTER_USER = 'REGISTER_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const REMOVE_CURRENT_USER_SUCCESS = 'REMOVE_CURRENT_USER_SUCCESS';
export const GET_ERRORS = 'GET_ERRORS';


export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_ERRORS = 'GET_PROFILE_ERRORS';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';