export const REGISTER_USER = 'REGISTER_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const REMOVE_CURRENT_USER_SUCCESS = 'REMOVE_CURRENT_USER_SUCCESS';
export const GET_ERRORS = 'GET_ERRORS';


export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_ERRORS = 'GET_PROFILE_ERRORS';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const CREATE_PROFILE = 'CREATE_PROFILE';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';


export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';

export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS';

export const ADD_EDUCATION = 'ADD_EDUCATION';
export const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS';

export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';

export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';

export const GET_PROFILE_BY_HANDLE = 'GET_PROFILE_BY_HANDLE';
export const GET_PROFILE_BY_HANDLE_SUCCESS = 'GET_PROFILE_BY_HANDLE_SUCCESS';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'